spring:
  application:
    name: limits
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:limits
    username: sa
    password:
  h2:
    console:
      settings:
        web-allow-others: false
      enabled: true
server:
  port: 8080

service:
  limits:
    amount: 10000
    reset-time: 0 0 0 * * *
